version: "3"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus_data:/nexus-data
    networks:
      - traefik-proxy
      - default
      
    # Control the number of instances deployed
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.router1.service=nexus
        - traefik.http.routers.router1.entrypoints=web
        - traefik.http.routers.router1.rule=Host(`nexus.${SVC_DOMAIN?}`)
        - traefik.http.services.nexus.loadbalancer.server.port=8081
        # configure port for hosted docker repository in Nexus
        - traefik.http.routers.router2.service=labdocker
        - traefik.http.routers.router2.entrypoints=web
        - traefik.http.routers.router2.rule=Host(`docker.${SVC_DOMAIN?}`)
        - traefik.http.services.labdocker.loadbalancer.server.port=8083
        - traefik.docker.network=traefik-proxy

networks:
  traefik-proxy:
    external: true

volumes:
  nexus_data:

