version: "3.3"

services:

  traefik:
    image: traefik:v2.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      labels:
        # Explicitly tell Traefik to expose this container
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.rule=Host(`traefik.${SVC_DOMAIN?}`)
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.docker.network=traefik-proxy
    ports:
      # The ssh port for gitlab
      - target: 2222
        published: 2222
        mode: host
      # The HTTP port
      - target: 80
        published: 80
        mode: host
      # The Web UI (enabled by --api)
      - target: 8080
        published: 8080
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
      - default
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
