[Global]
  CheckNewVersion = false
  SendAnonymousUsage = false

[accessLog]
  filePath = "/access.log"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.ssh]
    address = ":2222"

[providers]
  [providers.docker]
    exposedbydefault = false
    swarmMode = true

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"

[api]
  dashboard = true
  insecure = true
  debug = true
